### PR TITLE
Add the first version of the OpenAPI documentation

### PR DESCRIPTION
**Pull request by karakanb**
Hi there,

I saw in one of the issues that contributions regarding OpenAPI docs would be welcome, so I went ahead and created one. There are things missing here and there, such as contact information, but I believe this may provide us a basis to improve upon.

You can see the rendered version by copying and pasting the YAML into [Swagger Editor](https://editor.swagger.io/#). It roughly looks like as follows:
image

I tried to copy the examples and definitions from the existing documentation for consistency.

### CODE REVIEW

**Comment by gulien** [comment]
Thank you for this PR! I think it is RTM?

**Comment by karakanb** [comment]
It is ready to merge if you think it is good. 👍

**Comment by gulien** [comment]
Should we add a link somewhere in the documentation?

**Comment by karakanb** [comment]
Makes sense, any preference?

**Comment by gulien** [comment]
Maybe in the link section? https://github.com/thecodingmachine/gotenberg/blob/master/build/docs/content/15-links.md (`make docs` before committing)

**Comment by gulien** [comment]
Thank you @karakanb!

**Pull request merged**
