### PR TITLE
PDF/A support and HTML to PDF support for the Office endpoint 

### LINKED ISSUE #120: PDF/A conversions
Would it be possible to add a environment variable to enable converting to pdf/a instead of pdf 1.5?

It looks like unoconv does this when you specify `-eSelectPdfVersion=1`           
Alternatively you need a prop called "SelectPdfVersion" with value 1 in the `registrymodifications.xcu` generated by LibreOffice.

I tried creating a `gotenberg.yml` config file but it doesn't look like that is being used anymore.

----
Edit: I don't know how to apply labels, so can someone please tag this as a question...

### PR DESCRIPTION
**Pull request by leonvanderiet**
A similar PR may already be submitted!
Please search among the [pull requests](../../../pulls) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

For more information, see the [CONTRIBUTING](CONTRIBUTING.md) guide.

**Summary**

Add the possibility to generate PDF/A compliant output using the Office API
Add the possibility to generate PDF from HTML using the Office API, by whitelisting the .html extension.

This PR implements the following **features**
* [ X] Issue #120 

We needed a way to generate PDF/A from a HTML source. Unoconv was already able to do this, but needs an extra -export SelectPdfVersion=1 to the commandline. Because html file format isn't whitelisted for the /convert/office API and the headless chromium path isn't able to generate PDF/A we also whitelisted .html as a valid source

Because the headless chromium path isn't able to generate PDF/A  

**Test plan (required)**

Leons-MacBook-Pro:gotenberg leon$ make lint
make workspace
make base
docker build --build-arg GOTENBERG_USER_GID=1001 --build-arg GOTENBERG_USER_UID=1001 -t thecodingmachine/gotenberg:base -f build/base/Dockerfile .
Sending build context to Docker daemon  33.12MB
Step 1/13 : FROM debian:buster-slim
 ---> 2f14a0fb67b9
Step 2/13 : RUN echo "deb http://httpredir.debian.org/debian/ buster main contrib non-free" > /etc/apt/sources.list &&    apt-get update &&    apt-get install -y curl wget gnupg ttf-mscorefonts-installer procps
 ---> Using cache
 ---> e6f4bfe8df0d
Step 3/13 : RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - &&    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list &&    apt-get update &&    apt-get -y --allow-unauthenticated install google-chrome-stable
 ---> Using cache
 ---> 2d8e407de967
Step 4/13 : RUN mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1 &&    echo "deb http://httpredir.debian.org/debian/ buster-backports main contrib non-free" >> /etc/apt/sources.list &&    apt-get update &&    apt-get -t buster-backports -y install libreoffice
 ---> Using cache
 ---> 9758c4d10264
Step 5/13 : ENV UNO_URL=https://raw.githubusercontent.com/dagwieers/unoconv/master/unoconv
 ---> Using cache
 ---> bbbb9ffabda3
Step 6/13 : RUN curl -Ls $UNO_URL -o /usr/bin/unoconv &&    chmod +x /usr/bin/unoconv &&    ln -s /usr/bin/python3 /usr/bin/python &&    unoconv --version
 ---> Using cache
 ---> a752dd8e0fc9
Step 7/13 : RUN apt-get -y install pdftk
 ---> Using cache
 ---> bb84270aa839
Step 8/13 : RUN apt-get install -y     culmus     fonts-beng     fonts-hosny-amiri     fonts-lklug-sinhala     fonts-lohit-guru     fonts-lohit-knda     fonts-samyak-gujr     fonts-samyak-mlym     fonts-samyak-taml     fonts-sarai     fonts-sil-abyssinica     fonts-sil-padauk     fonts-telu     fonts-thai-tlwg     fonts-liberation     ttf-wqy-zenhei     fonts-arphic-uming     fonts-ipafont-mincho     fonts-ipafont-gothic     fonts-unfonts-core
 ---> Using cache
 ---> 34cf0ded153b
Step 9/13 : COPY build/base/fonts/* /usr/local/share/fonts/
 ---> Using cache
 ---> 499d0436d248
Step 10/13 : COPY build/base/fonts.conf /etc/fonts/conf.d/100-gotenberg.conf
 ---> Using cache
 ---> ba53659b6864
Step 11/13 : ARG GOTENBERG_USER_GID=1001
 ---> Using cache
 ---> af26f93c4348
Step 12/13 : ARG GOTENBERG_USER_UID=1001
 ---> Using cache
 ---> 8a9f66d58d09
Step 13/13 : RUN groupadd --gid ${GOTENBERG_USER_GID} gotenberg   && useradd --uid ${GOTENBERG_USER_UID} --gid gotenberg --shell /bin/bash --home /gotenberg --no-create-home gotenberg   && mkdir /gotenberg   && chown gotenberg: /gotenberg
 ---> Using cache
 ---> 3367aef39b80
Successfully built 3367aef39b80
Successfully tagged thecodingmachine/gotenberg:base
docker build --build-arg GOLANG_VERSION=1.13 -t thecodingmachine/gotenberg:workspace -f build/workspace/Dockerfile . 
Sending build context to Docker daemon  33.12MB
Step 1/11 : ARG GOLANG_VERSION
Step 2/11 : FROM golang:${GOLANG_VERSION}-stretch as golang
 ---> 4fe257ac564c
Step 3/11 : FROM thecodingmachine/gotenberg:base
 ---> 3367aef39b80
Step 4/11 : RUN apt-get update && apt-get install -y --no-install-recommends         git 		g++ 		gcc 		libc6-dev 		make 		pkg-config 	&& rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9129edc8e264
Step 5/11 : COPY --from=golang /usr/local/go /usr/local/go
 ---> Using cache
 ---> b84aae692ae5
Step 6/11 : ENV GOPATH /gotenberg/go
 ---> Using cache
 ---> 22d11e9d6705
Step 7/11 : ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
 ---> Using cache
 ---> e15c7213a766
Step 8/11 : RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" &&    chmod -R 777 "$GOPATH"
 ---> Using cache
 ---> 6bf2668d47e9
Step 9/11 : USER gotenberg
 ---> Using cache
 ---> 28c0f28ad2fb
Step 10/11 : RUN go version &&    go env
 ---> Using cache
 ---> 90bcc11aad5f
Step 11/11 : USER root
 ---> Using cache
 ---> 7d979f5ae4e3
Successfully built 7d979f5ae4e3
Successfully tagged thecodingmachine/gotenberg:workspace
docker build --build-arg GOLANGCI_LINT_VERSION=1.20.1 -t thecodingmachine/gotenberg:lint -f build/lint/Dockerfile .
Sending build context to Docker daemon  33.12MB
Step 1/9 : FROM thecodingmachine/gotenberg:workspace
 ---> 7d979f5ae4e3
Step 2/9 : ARG GOLANGCI_LINT_VERSION
 ---> Using cache
 ---> c9759f433328
Step 3/9 : RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /usr/local/bin v${GOLANGCI_LINT_VERSION} &&    golangci-lint --version
 ---> Using cache
 ---> cdc2f5af87b4
Step 4/9 : USER gotenberg
 ---> Using cache
 ---> 7e3b996a34ab
Step 5/9 : WORKDIR /gotenberg/lint
 ---> Using cache
 ---> 0cec97f6ef23
Step 6/9 : COPY --chown=gotenberg:gotenberg go.mod go.sum ./
 ---> Using cache
 ---> 8f887e7bc5d8
Step 7/9 : RUN go mod download &&    go mod verify
 ---> Using cache
 ---> a7aa611752d1
Step 8/9 : COPY --chown=gotenberg:gotenberg . .
 ---> 1c3d9ee4c131
Step 9/9 : CMD ["golangci-lint", "run" ,"--tests=false", "--enable-all", "--disable=dupl", "--disable=funlen", "--disable=wsl", "--disable=gocognit" ]
 ---> Running in 4810c2f773ca
Removing intermediate container 4810c2f773ca
 ---> 79f2bc0d38e5
Successfully built 79f2bc0d38e5
Successfully tagged thecodingmachine/gotenberg:lint
docker run --rm thecodingmachine/gotenberg:lint
Leons-MacBook-Pro:gotenberg leon$ make tests
make workspace
make base
docker build --build-arg GOTENBERG_USER_GID=1001 --build-arg GOTENBERG_USER_UID=1001 -t thecodingmachine/gotenberg:base -f build/base/Dockerfile .
Sending build context to Docker daemon  33.12MB
Step 1/13 : FROM debian:buster-slim
 ---> 2f14a0fb67b9
Step 2/13 : RUN echo "deb http://httpredir.debian.org/debian/ buster main contrib non-free" > /etc/apt/sources.list &&    apt-get update &&    apt-get install -y curl wget gnupg ttf-mscorefonts-installer procps
 ---> Using cache
 ---> e6f4bfe8df0d
Step 3/13 : RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - &&    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list &&    apt-get update &&    apt-get -y --allow-unauthenticated install google-chrome-stable
 ---> Using cache
 ---> 2d8e407de967
Step 4/13 : RUN mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1 &&    echo "deb http://httpredir.debian.org/debian/ buster-backports main contrib non-free" >> /etc/apt/sources.list &&    apt-get update &&    apt-get -t buster-backports -y install libreoffice
 ---> Using cache
 ---> 9758c4d10264
Step 5/13 : ENV UNO_URL=https://raw.githubusercontent.com/dagwieers/unoconv/master/unoconv
 ---> Using cache
 ---> bbbb9ffabda3
Step 6/13 : RUN curl -Ls $UNO_URL -o /usr/bin/unoconv &&    chmod +x /usr/bin/unoconv &&    ln -s /usr/bin/python3 /usr/bin/python &&    unoconv --version
 ---> Using cache
 ---> a752dd8e0fc9
Step 7/13 : RUN apt-get -y install pdftk
 ---> Using cache
 ---> bb84270aa839
Step 8/13 : RUN apt-get install -y     culmus     fonts-beng     fonts-hosny-amiri     fonts-lklug-sinhala     fonts-lohit-guru     fonts-lohit-knda     fonts-samyak-gujr     fonts-samyak-mlym     fonts-samyak-taml     fonts-sarai     fonts-sil-abyssinica     fonts-sil-padauk     fonts-telu     fonts-thai-tlwg     fonts-liberation     ttf-wqy-zenhei     fonts-arphic-uming     fonts-ipafont-mincho     fonts-ipafont-gothic     fonts-unfonts-core
 ---> Using cache
 ---> 34cf0ded153b
Step 9/13 : COPY build/base/fonts/* /usr/local/share/fonts/
 ---> Using cache
 ---> 499d0436d248
Step 10/13 : COPY build/base/fonts.conf /etc/fonts/conf.d/100-gotenberg.conf
 ---> Using cache
 ---> ba53659b6864
Step 11/13 : ARG GOTENBERG_USER_GID=1001
 ---> Using cache
 ---> af26f93c4348
Step 12/13 : ARG GOTENBERG_USER_UID=1001
 ---> Using cache
 ---> 8a9f66d58d09
Step 13/13 : RUN groupadd --gid ${GOTENBERG_USER_GID} gotenberg   && useradd --uid ${GOTENBERG_USER_UID} --gid gotenberg --shell /bin/bash --home /gotenberg --no-create-home gotenberg   && mkdir /gotenberg   && chown gotenberg: /gotenberg
 ---> Using cache
 ---> 3367aef39b80
Successfully built 3367aef39b80
Successfully tagged thecodingmachine/gotenberg:base
docker build --build-arg GOLANG_VERSION=1.13 -t thecodingmachine/gotenberg:workspace -f build/workspace/Dockerfile . 
Sending build context to Docker daemon  33.12MB
Step 1/11 : ARG GOLANG_VERSION
Step 2/11 : FROM golang:${GOLANG_VERSION}-stretch as golang
 ---> 4fe257ac564c
Step 3/11 : FROM thecodingmachine/gotenberg:base
 ---> 3367aef39b80
Step 4/11 : RUN apt-get update && apt-get install -y --no-install-recommends         git 		g++ 		gcc 		libc6-dev 		make 		pkg-config 	&& rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9129edc8e264
Step 5/11 : COPY --from=golang /usr/local/go /usr/local/go
 ---> Using cache
 ---> b84aae692ae5
Step 6/11 : ENV GOPATH /gotenberg/go
 ---> Using cache
 ---> 22d11e9d6705
Step 7/11 : ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
 ---> Using cache
 ---> e15c7213a766
Step 8/11 : RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" &&    chmod -R 777 "$GOPATH"
 ---> Using cache
 ---> 6bf2668d47e9
Step 9/11 : USER gotenberg
 ---> Using cache
 ---> 28c0f28ad2fb
Step 10/11 : RUN go version &&    go env
 ---> Using cache
 ---> 90bcc11aad5f
Step 11/11 : USER root
 ---> Using cache
 ---> 7d979f5ae4e3
Successfully built 7d979f5ae4e3
Successfully tagged thecodingmachine/gotenberg:workspace
./scripts/tests.sh thecodingmachine 0
Sending build context to Docker daemon  33.12MB
Step 1/7 : FROM thecodingmachine/gotenberg:workspace
 ---> 7d979f5ae4e3
Step 2/7 : USER gotenberg
 ---> Using cache
 ---> 5a7a2c1d51af
Step 3/7 : WORKDIR /gotenberg/tests
 ---> Using cache
 ---> 964e8b765d3f
Step 4/7 : COPY --chown=gotenberg:gotenberg go.mod go.sum ./
 ---> Using cache
 ---> 8bd00ad46f41
Step 5/7 : RUN go mod download &&    go mod verify
 ---> Using cache
 ---> be91fa43ccbe
Step 6/7 : COPY --chown=gotenberg:gotenberg . .
 ---> Using cache
 ---> 1c9b36822d7f
Step 7/7 : ENTRYPOINT [ "build/tests/docker-entrypoint.sh" ]
 ---> Using cache
 ---> 2e0b893fe14b
Successfully built 2e0b893fe14b
Successfully tagged thecodingmachine/gotenberg:tests
++ whoami
+ CURRENT_USER=gotenberg
+ '[' gotenberg '!=' gotenberg ']'
+ go run test/cmd/chrome.go
+ '[' 0 = 1 ']'
+ go test -race -cover ./...
?   	github.com/thecodingmachine/gotenberg/cmd/gotenberg	[no test files]
ok  	github.com/thecodingmachine/gotenberg/internal/app/xhttp	41.472s	coverage: 89.5% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/app/xhttp/pkg/context	1.078s	coverage: 87.7% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/app/xhttp/pkg/resource	1.076s	coverage: 90.6% of statements
?   	github.com/thecodingmachine/gotenberg/internal/pkg/chrome	[no test files]
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/conf	1.084s	coverage: 100.0% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/normalize	1.033s	coverage: 83.3% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/printer	49.891s	coverage: 80.0% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/xassert	1.022s	coverage: 85.6% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/xcontext	2.018s	coverage: 100.0% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/xerror	1.019s	coverage: 100.0% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/xexec	1.043s	coverage: 85.9% of statements
?   	github.com/thecodingmachine/gotenberg/internal/pkg/xlog	[no test files]
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/xrand	1.074s	coverage: 100.0% of statements
ok  	github.com/thecodingmachine/gotenberg/internal/pkg/xtime	1.024s	coverage: 100.0% of statements
?   	github.com/thecodingmachine/gotenberg/test	[no test files]
?   	github.com/thecodingmachine/gotenberg/test/cmd	[no test files]

**Closing issues**

Fixes #120 

**Checklist**

- [x] Have you followed the guidelines in our [CONTRIBUTING](CONTRIBUTING.md) guide?
- [x] Have you lint your code locally prior to submission (`make lint`)?
- [x ] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally (`make tests`)?
- [x] Have you updated the documentation (Markdown files under `build > docs > content` and then `make doc`)?
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by gulien** [comment]
Hello @leonvanderiet 

Thanks for the PR! 

I'm currently quite busy but I'll check it 👍

**Comment by Simplici** [comment]
hello, i need to use this feature. when can this get merged and released?

**Comment by gulien** [comment]
Hello sorry for the delay I was sick the last two weeks...

I do not like the idea of having LibreOffice converting HTML: it may confuse users as the resulting PDF will not be the same as the one from Google Chrome.

Still, I understand that PDF/A output is something needed by some of you. I'll try to figure this out in the next version of Gotenberg.

In the meantime, if you want this feature, you may clone the branch from @leonvanderiet and build the project yourself using:

```bash
make publish DOCKER_REGISTRY=your_registry DOCKER_USER=registry_user DOCKER_PASSWORD=registry_password VERSION=6.2.0
```

Or building locally:

```bash
make image DOCKER_REGISTRY=your_registry VERSION=6.2.0
```

**Comment by leonvanderiet** [comment]
> Hello sorry for the delay I was sick the last two weeks...
> 
> I do not like the idea of having LibreOffice converting HTML: it may confuse users as the resulting PDF will not be the same as the one from Google Chrome.
> 
> Still, I understand that PDF/A output is something needed by some of you. I'll try to figure this out in the next version of Gotenberg.

Hello @gulien 

I understand that Chrome is the preferred way to generate HTML -> PDF and this is still the case if users are using the endpoints as decribed in the documentation. Otherwise we can clarify it with an extra note in the documentation of the office endpoint?

**Comment by davidsudespacho** [comment]
Hi @gulien , great project, do you plan to implement PDF/A output coming soon ??

**Comment by gulien** [comment]
Hello @davidsudespacho,

I'm currently working on the new version of Gotenberg, and it's on my TODO list. No ETA yet though.

**Pull request closed without merging**
